project         = "justme-test"
region          = "europe-west2"
zone            = "europe-west2-a"
#machine_type   = "n1-standard-4"   # CPU 4 / MEM 15
machine_type    = "n1-standard-8"   # CPU 8 / MEM 30
machine_image   = "ubuntu-2004-focal-v20200917"
disk_size       = "100"
network         = "vpc-1"
subnetwork      = "vpc-1-subnet-1-eu-west-2"
