project         = "justme-test"
region          = "europe-west2"
zone            = "europe-west2-a"
machine_type    = "e2-medium"
machine_image   = "ubuntu-2004-focal-v20200917"
disk_size       = "30"
network         = "vpc-1"
subnetwork      = "vpc-1-subnet-1-eu-west-2"
